[package]
name = "rustoleum"
version = "0.2.0"
edition = "2021"

[lib]
name = "rustoleum"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.9.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
